// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microscopes/io/schema.proto

#ifndef PROTOBUF_microscopes_2fio_2fschema_2eproto__INCLUDED
#define PROTOBUF_microscopes_2fio_2fschema_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace microscopes {
namespace io {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_microscopes_2fio_2fschema_2eproto();
void protobuf_AssignDesc_microscopes_2fio_2fschema_2eproto();
void protobuf_ShutdownFile_microscopes_2fio_2fschema_2eproto();

class CRP;

// ===================================================================

class CRP : public ::google::protobuf::Message {
 public:
  CRP();
  virtual ~CRP();

  CRP(const CRP& from);

  inline CRP& operator=(const CRP& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CRP& default_instance();

  void Swap(CRP* other);

  // implements Message ----------------------------------------------

  CRP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CRP& from);
  void MergeFrom(const CRP& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float alpha = 1;
  inline bool has_alpha() const;
  inline void clear_alpha();
  static const int kAlphaFieldNumber = 1;
  inline float alpha() const;
  inline void set_alpha(float value);

  // @@protoc_insertion_point(class_scope:microscopes.io.CRP)
 private:
  inline void set_has_alpha();
  inline void clear_has_alpha();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  float alpha_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_microscopes_2fio_2fschema_2eproto();
  friend void protobuf_AssignDesc_microscopes_2fio_2fschema_2eproto();
  friend void protobuf_ShutdownFile_microscopes_2fio_2fschema_2eproto();

  void InitAsDefaultInstance();
  static CRP* default_instance_;
};
// ===================================================================


// ===================================================================

// CRP

// required float alpha = 1;
inline bool CRP::has_alpha() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CRP::set_has_alpha() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CRP::clear_has_alpha() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CRP::clear_alpha() {
  alpha_ = 0;
  clear_has_alpha();
}
inline float CRP::alpha() const {
  return alpha_;
}
inline void CRP::set_alpha(float value) {
  set_has_alpha();
  alpha_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace io
}  // namespace microscopes

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_microscopes_2fio_2fschema_2eproto__INCLUDED
