# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microscopes/io/schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='microscopes/io/schema.proto',
  package='microscopes.io',
  serialized_pb='\n\x1bmicroscopes/io/schema.proto\x12\x0emicroscopes.io\"\x14\n\x03\x43RP\x12\r\n\x05\x61lpha\x18\x01 \x02(\x02')




_CRP = _descriptor.Descriptor(
  name='CRP',
  full_name='microscopes.io.CRP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alpha', full_name='microscopes.io.CRP.alpha', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['CRP'] = _CRP

class CRP(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CRP

  # @@protoc_insertion_point(class_scope:microscopes.io.CRP)


# @@protoc_insertion_point(module_scope)
