# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microscopes/io/schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='microscopes/io/schema.proto',
  package='microscopes.io',
  serialized_pb='\n\x1bmicroscopes/io/schema.proto\x12\x0emicroscopes.io\"\x14\n\x03\x43RP\x12\r\n\x05\x61lpha\x18\x01 \x02(\x02\"Q\n\x14\x42\x65taBernoulliNonConj\x1a%\n\x06Shared\x12\r\n\x05\x61lpha\x18\x01 \x02(\x02\x12\x0c\n\x04\x62\x65ta\x18\x02 \x02(\x02\x1a\x12\n\x05Group\x12\t\n\x01p\x18\x01 \x02(\x02\"\x8e\x01\n\x14NormalInverseWishart\x1a>\n\x06Shared\x12\x0b\n\x03mu0\x18\x01 \x03(\x02\x12\x0e\n\x06lambda\x18\x02 \x02(\x02\x12\x0b\n\x03psi\x18\x03 \x03(\x02\x12\n\n\x02nu\x18\x04 \x02(\x02\x1a\x36\n\x05Group\x12\r\n\x05\x63ount\x18\x01 \x02(\x05\x12\r\n\x05sum_x\x18\x02 \x03(\x02\x12\x0f\n\x07sum_xxT\x18\x03 \x03(\x02')




_CRP = _descriptor.Descriptor(
  name='CRP',
  full_name='microscopes.io.CRP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alpha', full_name='microscopes.io.CRP.alpha', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=67,
)


_BETABERNOULLINONCONJ_SHARED = _descriptor.Descriptor(
  name='Shared',
  full_name='microscopes.io.BetaBernoulliNonConj.Shared',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alpha', full_name='microscopes.io.BetaBernoulliNonConj.Shared.alpha', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta', full_name='microscopes.io.BetaBernoulliNonConj.Shared.beta', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=93,
  serialized_end=130,
)

_BETABERNOULLINONCONJ_GROUP = _descriptor.Descriptor(
  name='Group',
  full_name='microscopes.io.BetaBernoulliNonConj.Group',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='microscopes.io.BetaBernoulliNonConj.Group.p', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=132,
  serialized_end=150,
)

_BETABERNOULLINONCONJ = _descriptor.Descriptor(
  name='BetaBernoulliNonConj',
  full_name='microscopes.io.BetaBernoulliNonConj',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_BETABERNOULLINONCONJ_SHARED, _BETABERNOULLINONCONJ_GROUP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=150,
)


_NORMALINVERSEWISHART_SHARED = _descriptor.Descriptor(
  name='Shared',
  full_name='microscopes.io.NormalInverseWishart.Shared',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mu0', full_name='microscopes.io.NormalInverseWishart.Shared.mu0', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lambda', full_name='microscopes.io.NormalInverseWishart.Shared.lambda', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='psi', full_name='microscopes.io.NormalInverseWishart.Shared.psi', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nu', full_name='microscopes.io.NormalInverseWishart.Shared.nu', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=177,
  serialized_end=239,
)

_NORMALINVERSEWISHART_GROUP = _descriptor.Descriptor(
  name='Group',
  full_name='microscopes.io.NormalInverseWishart.Group',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='microscopes.io.NormalInverseWishart.Group.count', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sum_x', full_name='microscopes.io.NormalInverseWishart.Group.sum_x', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sum_xxT', full_name='microscopes.io.NormalInverseWishart.Group.sum_xxT', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=241,
  serialized_end=295,
)

_NORMALINVERSEWISHART = _descriptor.Descriptor(
  name='NormalInverseWishart',
  full_name='microscopes.io.NormalInverseWishart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_NORMALINVERSEWISHART_SHARED, _NORMALINVERSEWISHART_GROUP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=153,
  serialized_end=295,
)

_BETABERNOULLINONCONJ_SHARED.containing_type = _BETABERNOULLINONCONJ;
_BETABERNOULLINONCONJ_GROUP.containing_type = _BETABERNOULLINONCONJ;
_NORMALINVERSEWISHART_SHARED.containing_type = _NORMALINVERSEWISHART;
_NORMALINVERSEWISHART_GROUP.containing_type = _NORMALINVERSEWISHART;
DESCRIPTOR.message_types_by_name['CRP'] = _CRP
DESCRIPTOR.message_types_by_name['BetaBernoulliNonConj'] = _BETABERNOULLINONCONJ
DESCRIPTOR.message_types_by_name['NormalInverseWishart'] = _NORMALINVERSEWISHART

class CRP(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CRP

  # @@protoc_insertion_point(class_scope:microscopes.io.CRP)

class BetaBernoulliNonConj(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Shared(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BETABERNOULLINONCONJ_SHARED

    # @@protoc_insertion_point(class_scope:microscopes.io.BetaBernoulliNonConj.Shared)

  class Group(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BETABERNOULLINONCONJ_GROUP

    # @@protoc_insertion_point(class_scope:microscopes.io.BetaBernoulliNonConj.Group)
  DESCRIPTOR = _BETABERNOULLINONCONJ

  # @@protoc_insertion_point(class_scope:microscopes.io.BetaBernoulliNonConj)

class NormalInverseWishart(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Shared(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _NORMALINVERSEWISHART_SHARED

    # @@protoc_insertion_point(class_scope:microscopes.io.NormalInverseWishart.Shared)

  class Group(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _NORMALINVERSEWISHART_GROUP

    # @@protoc_insertion_point(class_scope:microscopes.io.NormalInverseWishart.Group)
  DESCRIPTOR = _NORMALINVERSEWISHART

  # @@protoc_insertion_point(class_scope:microscopes.io.NormalInverseWishart)


# @@protoc_insertion_point(module_scope)
