package:
  name: microscopes-common
  version: "0.1.0"

source:
  git_url: https://github.com/datamicroscopes/common.git

requirements:
  build:
    - cmake
    - python
    - numpy
    - cython 0.20.2
    - distributions
    - libprotobuf
    - eigen3
  run:
    - python
    - numpy
    - scipy
    - pymc
    - distributions
    - libprotobuf
    - protobuf

test:
  imports:
    - microscopes
    - microscopes.common
    - microscopes.io

about:
  home: https://github.com/datamicroscopes/common
