package:
  name: microscopes-common
  version: "0.1.1"

source:
  git_url: https://github.com/datamicroscopes/common.git

requirements:
  build:
    - cmake
    - python
    - numpy ==1.8.2
    - cython >=0.22
    - distributions >=2.0.23
    - libprotobuf
    - eigen3
  run:
    - python
    - numpy ==1.8.2
    - scipy
    - distributions >=2.0.23
    - libprotobuf
    - protobuf

test:
  imports:
    - microscopes
    - microscopes.common
    - microscopes.io

about:
  home: https://github.com/datamicroscopes/common
